server:
  port: 8900
spring:
  application:
    name: consumer-feign
eureka:
  instance:
    hostname: localhost
    # 发呆时间，即服务失效时间（缺省为90s）,就是超过15秒没有续约就会从注册表中剔除
    lease-expiration-duration-in-seconds: 15
    # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka
PROVIDER-USER:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
# 在feign使用hystrix
feign:
  hystrix:
    enabled: true
# 熔断器DashBoard: actuator在boot2.0调整后开关web端点的配置，*代表开启所有
management:
  endpoints:
    web:
      exposure:
        include: "*"
